import { Rajdhani } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/page";
import KanabanProvider from "@/KanabanProvider/KanabanProvider";
import QueryProvider from "@/QueryProvider/QueryProvider";
import { Toaster } from "react-hot-toast";
const rajdhani = Rajdhani({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: "Kanaban-Board",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${rajdhani.className} `}>
        <QueryProvider>
          <KanabanProvider>
            <Header />
            <div className="bg-[#f3f4f6] h-screen">{children}</div>
            <Toaster />
          </KanabanProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
